<a href="https://colab.research.google.com/github/SakshamTolani/ml/blob/main/23419MCA047_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
def normalize_vector(v):
    return v / np.linalg.norm(v)

In [ ]:
def calcMatrix(matrix, var):
  if var=='u':
    B = np.dot(matrix,matrix.T)
  elif var=='v':
    B = np.dot(matrix.T,matrix)

  eigenvalues, eigenvectors = np.linalg.eigh(B)
  ncols = np.argsort(eigenvalues)[::-1]
  eigenvalues = eigenvalues[ncols]
  eigenvectors = eigenvectors[:,ncols]
  # if var=='u':
  #   return eigenvectors
  # elif var=='v':
  #   return eigenvectors
  eigenvectors = np.array([normalize_vector(eigenvectors[:, i]) for i in range(eigenvectors.shape[1])]).T
  return eigenvectors


In [ ]:
def calcSigma(matrix):
  if matrix.shape[0] > matrix.shape[1]:
    gram_matrix = np.dot(matrix.T,matrix)
  else:
    gram_matrix = np.dot(matrix,matrix.T)

  eigenvalues, _ = np.linalg.eigh(gram_matrix)
  ncols = np.argsort(eigenvalues)[::-1]
  eigenvalues = eigenvalues[ncols]
  singular_values = np.sqrt(np.abs(eigenvalues))
  np.sort(singular_values)[::-1]

  Sigma = np.zeros_like(matrix, dtype=np.float64)
  np.fill_diagonal(Sigma, singular_values)

  return Sigma


In [ ]:
A = np.array([[1,1,0],[0,1,1]])

In [ ]:
U = calcMatrix(A,'u')
V_T= calcMatrix(A,'v')
Sigma = calcSigma(A)

In [ ]:
U

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [ ]:
V_T

array([[ 4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
       [ 8.16496581e-01,  9.71445147e-17,  5.77350269e-01],
       [ 4.08248290e-01, -7.07106781e-01, -5.77350269e-01]])

In [ ]:
Sigma

array([[1.73205081, 0.        , 0.        ],
       [0.        , 1.        , 0.        ]])

In [ ]:
A_new = U@Sigma@V_T

In [ ]:
A_new

array([[ 2.77350098, -1.10940039, -3.32820118],
       [-3.05085108, -5.26965186, -4.99230177]])

In [ ]:
u,s,vt = np.linalg.svd(A)

In [ ]:
vt

array([[ 0.26001965,  0.65919758,  0.70558368],
       [ 0.89132415,  0.11719389, -0.43795758],
       [ 0.37139068, -0.74278135,  0.55708601]])