<a href="https://colab.research.google.com/github/SakshamTolani/ml/blob/main/23419MCA047.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = {
    'Machine': [1,2,3,4,5,6,7,8,9,10],
    'Speed': [100,105,95,110,102,97,103,90,107,104],
    'Temp': [60,63,57,65,61,58,62,59,64,60],
    'Vibration': [12,15,10,18,14,13,16,11,17,13],
    'Energy': [30,33,29,35,32,31,34,30,34,32],
    'Maintanence': [5,7,4,8,6,5,7,5,8,6]
}

STEPS FOR PCA:


*   Standardize the data
*   Calculate covariance matrix of standardized data (Use Transpose)
*   Calculate Eigenvalues and Eigenvectors of the data (Sort them)
*   Check Explained Variance of the eigenvalues
*   Select number of components required after applying PCA
*   Take dot product of ncomponents of eigenvectors with standardized data.







In [ ]:
df = pd.DataFrame(data)
df = df.drop(columns=['Machine'])
df

Speed  Temp  Vibration  Energy  Maintanence
0    100    60         12      30            5
1    105    63         15      33            7
2     95    57         10      29            4
3    110    65         18      35            8
4    102    61         14      32            6
5     97    58         13      31            5
6    103    62         16      34            7
7     90    59         11      30            5
8    107    64         17      34            8
9    104    60         13      32            6

In [ ]:
standardized_data = (df - np.mean(df, axis=0))/np.std(df, axis=0)
standardized_data

Speed      Temp  Vibration    Energy  Maintanence
0 -0.229774 -0.364698  -0.769919 -1.054093    -0.846154
1  0.653972  0.850963   0.445742  0.527046     0.692308
2 -1.113519 -1.580360  -1.580360 -1.581139    -1.615385
3  1.537717  1.661404   1.661404  1.581139     1.461538
4  0.123724  0.040522   0.040522  0.000000    -0.076923
5 -0.760021 -1.175139  -0.364698 -0.527046    -0.846154
6  0.300473  0.445742   0.850963  1.054093     0.692308
7 -1.997265 -0.769919  -1.175139 -1.054093    -0.846154
8  1.007470  1.256183   1.256183  1.054093     1.461538
9  0.477223 -0.364698  -0.364698  0.000000    -0.076923

In [ ]:
cov_mat = np.cov(standardized_data.T)
cov_mat

array([[1.11111111, 0.95735197, 0.97326804, 0.9626011 , 0.96230055],
       [0.95735197, 1.11111111, 1.03813173, 1.02038966, 1.07712444],
       [0.97326804, 1.03813173, 1.11111111, 1.09157964, 1.07712444],
       [0.9626011 , 1.02038966, 1.09157964, 1.11111111, 1.08112057],
       [0.96230055, 1.07712444, 1.07712444, 1.08112057, 1.11111111]])

In [ ]:
eigenvalues,eigenvectors = np.linalg.eigh(cov_mat)
eigenvalues

array([0.00952777, 0.02430958, 0.10551071, 0.20555348, 5.21065402])

In [ ]:
eigenvectors

array([[ 0.02927106,  0.05658758,  0.01660097, -0.90254278, -0.42553729],
       [-0.37434877, -0.20618574, -0.7669525 ,  0.17152851, -0.44689179],
       [ 0.29076396, -0.73737662,  0.36231479,  0.1841433 , -0.45447912],
       [-0.59935907,  0.35050304,  0.5123241 ,  0.22527516, -0.45242839],
       [ 0.64438438,  0.53638477, -0.13326773,  0.26708958, -0.45602963]])

In [ ]:
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:,idx]

In [ ]:
explained_variance = np.cumsum(eigenvalues)/np.sum(eigenvalues)
explained_variance

array([0.93791772, 0.97491735, 0.99390928, 0.998285  , 1.        ])

In [ ]:
# n_components = np.argmax(explained_variance >= 0.50) + 1
n_components = 2

In [ ]:
top_eigenvectors = eigenvectors[:,:n_components]
top_eigenvectors

array([[ 0.02927106,  0.05658758],
       [-0.37434877, -0.20618574],
       [ 0.29076396, -0.73737662],
       [-0.59935907,  0.35050304],
       [ 0.64438438,  0.53638477]])

In [ ]:
# pca = np.dot(standardized_data,top_eigenvectors)
pca = standardized_data@top_eigenvectors
pca.rename({'PC1': 'PCA1', 'PC2': 'PCA2'}, axis=1, inplace=True)
print(pca)

          0         1
0 -0.007534 -0.193413
1 -0.039586  0.088945
2  0.006241  0.007495
3 -0.099735 -0.142482
4 -0.049334 -0.072494
5  0.082266 -0.170386
6 -0.096306  0.038423
7 -0.025400  0.088920
8  0.234504  0.025133
9 -0.005116  0.329860
